nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.1.cjs
npmRegistries:
  //npm.fontawesome.com:
    npmAuthToken: 64BD9AE1-8728-472E-BD25-9E765CEA86CE

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"

packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
